apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - edge1
                - edge2
                - edge3
      containers:
      - name: worker
        image: fl-worker:local
        imagePullPolicy: Always
        env:
        - name: MASTER_ADDR
          value: "http://master-service:5000"
